config/routes.rb
Rails.application.routes.draw do
  devise_for :users,  controllers:{ 
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    :omniauth_callbacks => "users/omniauth_callbacks"

   }

    root to: 'home#home'
    resources :home
    resources :events
    post 'create_feedback' => "events#create_feedback"
    get  'states' => "events#state"
    resources :categories
    resources :users
    resources :registrations

    resources :rsvps, only: [:show,:create] do
    
      member do
      post :create_feedback
    end
    
    end
    namespace :api do
      resources :sessions, only: [:create, :destroy]
      resources :events, only: [:index]
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	layout 'application'
		def home
		end

		def index
			@events = Event.all
		end
end

app/views/home/home.html.erb
<h1>home</h1>

<%  if user_signed_in?%>
<div class="jumbotron">
  <div align="center">
    <%= link_to 'START' , home_index_path, :class => "btn btn-info" %>
</div>
      <p class="font-size">Free, Innovative Online RSVP, Registration & Event Management Tools To Help You Win Event Planning.
  </p>
</div>
<% end %>
<div class="row">
<div class="col-md-12">
<div class="col-md-4"><div class="well one"><h4 class="f-size"><strong>Step 1</strong></strong></h4><p class="margin-top">Send guests to my Event.rsvpify.com froma paper or digital  invitation or embed your RSVP on your website</p></div>
</div>
<div class="col-md-4"><div class="well  one"><h4 class="f-size"><strong>
	Step 2
</strong></h4><p class="margin-top">Your guests visit your online RSVP website and complete your customized online RSVP in minutes</p></div>
</div>
<div class="col-md-4"><div class="well one"><h4 class="f-size"><strong>
	Step 3
</strong></h4><p class="margin-top">You alwys know whome you havent't  heared from, who's coming and what there preference are</p></div>
</div>
</div>
</div>

app/views/home/index.html.erb
<table>                        
  <thead>                  
    <th class="th">Event_Name</th>
    <th class="th">Event_Date</th>
    <th class="th">Code</th>
    <th class="th">Description</th>
    <th class="th">Actions</th>
  </thead>
  <tbody>
    <% if @events.blank? %>
      <tr>
        <td colspan="5" class="text-center">
          No Event found, Please<%= link_to "click Here", new_event_path %>  to create new event.
        </td>
      </tr>
    <% else %>
      <% @events.each do |event| %>  
        <tr>
          <td class="td"><%= event.event_name %></td>  
          <td class="td"><%= event.event_date %></td> 
          <td class="td"><%= link_to rsvp_url(event.code),  rsvp_path(event.code) %></td>
          <td class="td"><%= event.description %></td> 
          <td class="td">|<%= link_to 'show', event_path(event) %>|&nbsp;&nbsp;|<%= link_to  'delete', event_path(event) , method: :delete %>|</td>
        </tr>
      <% end %> 
    <% end %> 
  </tbody>             
</table>           