config/routes.rb
Rails.application.routes.draw do
  devise_for :users,  controllers:{ 
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    :omniauth_callbacks => "users/omniauth_callbacks"

   }

    root to: 'home#home'
    resources :home
    resources :events
    post 'create_feedback' => "events#create_feedback"
    get  'states' => "events#state"
    resources :categories
    resources :users
    resources :registrations

    resources :rsvps, only: [:show,:create] do
    
      member do
      post :create_feedback
    end
    
    end
    namespace :api do
      resources :sessions, only: [:create, :destroy]
      resources :events, only: [:index]
    end

end

app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController
	before_action :authenticate_user!
	layout 'rsvps'
	def show
		@event = Event.where(code: params[:id]).last
		@feedback = @event.feedbacks.build
	end

	def create_feedback
		@event = Event.find(params[:id])
		params[:feedback][:response] = params[:feedback][:response].to_i
		feedback = @event.feedbacks.build(feedback_params)
		feedback.save
		render 'thank_you'
	end

	protected

	def feedback_params
		params.require(:feedback).permit(:email_id, :response, :message,  :no_of_peoples, user_infos_attributes: [:first_name, :last_name])
	end
	
end

app/views/rsvps/_user_info_fields.html.erb
<div class="row">
	<div class="col-md-6">
		<div  class="form-group">
			<%= f.text_field :first_name, class: 'form-control', placeholder: '*Enter First Name*' %>
		</div>
	</div>	
	<div class="col-md-6">
		<div class="form-group">
		<%= f.text_field :last_name, class: 'form-control',placeholder: '*Enter First Name*' %>
		</div>
	</div>

app/views/rsvps/show.html.erb
<div  class="well">
	<div class="row">
		<div class="col-md-12">
			<div class="col-md-4">
				<h1 class="name"><%=  @event.event_name %></h1>
				<br>
        <div class="form-group group">
				<%= @event.event_date %>
        </div><br>
				<%= image_tag(@event.category.image.url) %>
			</div>
			<div class="col-md-8">
				<h1 class="name">FeedBack</h1>
					<%= form_for @feedback, url: create_feedback_rsvp_path(@event.id) do |f| %>
          <div class="form-group">
            <%= f.text_field :email_id, class: 'form-control', placeholder: 'Enter Email Id', required: true %>
          </div>
          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <%= f.text_field :first_name, class: 'form-control', placeholder: 'Enter First Name', required: true %>
              </div>    
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <%= f.text_field :last_name, class: 'form-control', placeholder: 'Enter Last Name', required: true %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <%= f.select :response, options_for_select([["Yes", 0], ["Maybe", 1], ["No", 2]]), {prompt: 'will you be Attending?*'}, class: 'form-control', required: true %>
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <%= f.select :no_of_peoples, options_for_select((1..10).to_a),{prompt: 'No of people  Attending *' }, class: 'form-control', required: true, placeholder: "Enter Number Of People" %>
              </div>
            </div>
          </div>
          <div class="user-info-wraper">
            <%= f.fields_for :user_infos do |builder| %>
              <%= render 'user_info_fields', f: builder %>
            <% end %>
          </div>
          <div>
            <%=  link_to_add_fields 'Add  User  info', f, :user_infos %>
          </div>

          <div class="form-group">
            <%= f.text_field :mobile, class: 'form-control', placeholder: 'Enter Mobile Number',required: true %>
          </div>

          <div class="form-group">
            <%= f.text_area :message, class: 'form-control', placeholder: 'Enter Some Message', required: true %>
          </div>

          <div class="form-group">
            <%= f.submit "Submit feedback", class: 'btn btn-primary align: center' %>
          </div>
        <% end %>
				</div>
		  </div>

<script type="text/javascript">
  $("[data-form-prepend]").click(function(e) {
  var obj = $($(this).attr("data-form-prepend"));
  obj.find("input, select, textarea").each(function() {
    $(this).attr("name", function() {
      return $(this)
        .attr("name")
        .replace("new_record", new Date().getTime());
    });
  });
  obj.insertBefore(this);
  return false;
});
</script>

app/views/rsvps/thank_you.html.erb
<%= image_tag "thank-you-3d-red-rose.jpg" %>