config/routes.rb
Rails.application.routes.draw do
  devise_for :users,  controllers:{ 
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    :omniauth_callbacks => "users/omniauth_callbacks"

   }

    root to: 'home#home'
    resources :home
    resources :events
    post 'create_feedback' => "events#create_feedback"
    get  'states' => "events#state"
    resources :categories
    resources :users
    resources :registrations

    resources :rsvps, only: [:show,:create] do
    
      member do
      post :create_feedback
    end
    
    end
    namespace :api do
      resources :sessions, only: [:create, :destroy]
      resources :events, only: [:index]
    end

end

app/views/layouts/_events_nav.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid event-nav">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header ">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><%= image_tag "rsvp.png", :style => "    display: inline-block;
    height: 45px;
    width: 150px;
    margin-top: -5px;" %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
          <% if user_signed_in? %>
            <ul class="dropdown-menu">
            <li><%= link_to 'MyAccount',   edit_user_path(current_user) %></li><hr>
            <li><%= link_to 'My Events', home_index_path %></li><hr>
            <li><%= link_to 'logout', destroy_user_session_path, method: :delete %></li>
           <% else %>
           <li><%= link_to 'Login', new_user_session_path %></li>
           <% end %>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_index_navigation.html.erb
<nav class="navbar navbar-default1">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><%= image_tag "rsvp.png" , :style => "display: block;
    width: 190px;" %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        
       
        
      </ul>
     <ul class="nav navbar-nav1 navbar-right">
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
          <% if user_signed_in? %>
            <ul class="dropdown-menu">
            <li><%= link_to 'create New Event', new_event_path %></li>
            <li><%= link_to 'Manage Users' %></li>
            <li><%= link_to 'logout', destroy_user_session_path, method: :delete %></li>
           <% else %>
           <li><%= link_to 'Login', new_user_session_path %></li>
          <% end %>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_navigation.html.erb
 <nav class="navbar navbar-default1">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><%= image_tag "rsvp.png" , :style => "display: block;
    width: 190px; height: 60px;" %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        
       
        
      </ul>
     <ul class="nav navbar-nav1 navbar-right">
       <li><%= link_to 'Login', new_user_session_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_rsvps_nav.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid event-nav">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header ">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><%= image_tag "retina-logo.png", :style => "    display: inline-block;
    height: 45px;
    width: 150px;
    margin-top: -5px;" %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
          <% if user_signed_in? %>
            <ul class="dropdown-menu">
            <li><%= link_to 'MyAccount' %></li>
            <li><%= link_to 'Manage Users' %></li>
            <li><%= link_to 'logout', destroy_user_session_path, method: :delete %></li>
           <% else %>
           <li><%= link_to 'Login', new_user_session_path %></li>
           <% end %>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>RsvpifyApp</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
	<% if user_signed_in? %>
	<%= render  'layouts/index_navigation' %>
	<% else %>
		<%= render 'layouts/navigation' %>
		<% end %>
		
		<div class="container">
			<%= yield %>
		</div>
	</body>
</html>

app/views/layouts/events.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RsvpifyApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/css/bootstrap-datetimepicker.min.css" />

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js"></script>

  <%= csrf_meta_tags %>
</head>
<body class="eventbody">
<%= render 'layouts/events_nav' %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>
</html>

app/views/layouts/rsvps.html.erb
<!DOCTYPE html>
	<html>
		<head>
 			<title>RsvpifyApp</title>
  			<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  			<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  			<%= csrf_meta_tags %>
		</head>
		<body class="eventbody">
			<%= render 'layouts/events_nav' %>
				<p class="notice"><%= notice %></p>
				<p class="alert"><%= alert %></p>
		<%= yield %>
	</html>